# extract items useful for plotting from the history generated by the
# fallback `result` method:
function plotting_report(fields, scales, history)

    n_models = length(history)
    n_parameters = length(fields)

    A = Array{Any}(undef, (n_models, n_parameters))
    measurements = Vector{Float64}(undef, n_models)

    for j in eachindex(history)
        entry = history[j]
        A[j,:] = [recursive_getproperty(entry.model, fld) for fld in fields]
        measurements[j] = entry.measurement[1]
    end

    return plotting=(parameter_names=string.(fields) |> collect,
                     parameter_scales=scales |> collect,
                     parameter_values = A,
                     measurements = measurements)

end

# return a named tuple with some keys removed:
function delete(nt::NamedTuple, target_keys...)
    zipped = tuple(zip(keys(nt), values(nt))...)
    filtered = filter(zipped) do tup
        !(tup[1] in target_keys)
    end
    return (; filtered...)
end

# `SMB` is alias for `StatisticalMeasuresBase`
signature(measure) =
    if SMB.orientation(measure) == SMB.Loss()
        1
    elseif SMB.orientation(measure) == SMB.Score()
        -1
    else
        0
    end

# function to trim a string like "transformed_target_model_deterministic.model.K" to `N`
# characters. For example, if `N=20`, return `…model.K`. Used in plotrecipes.jl.
function trim(str, N)
    n = length(str)
    n <= N && return str
    fits = false
    parts = split(str, ".") |> reverse
    # removes parts until what remains fits, with room for ellipsis (1 character), or if
    # there is only one part left:
    while !fits && length(parts) > 1
        removed = pop!(parts)
        n -= length(removed) + 1 # the `1` is for the dot, `.`
        if n < N
            fits = true
        end
    end
    "…"*join(reverse(parts), ".")
end
